STAR_CMD = STAR \
--runThreadN 40 \
--runMode alignReads \
--readFilesCommand zcat \
--quantMode TranscriptomeSAM GeneCounts \
--twopassMode Basic \
--outSAMtype BAM Unsorted \
--outSAMunmapped None \
--genomeDir /home/lucas_pkuhpc/lustre2/yuyangyang/Genome/mm9_index/ 
STAR_RUN:
 pkurun-fat4way 1 16 $(STAR_CMD) --readFilesIn /home/lucas_pkuhpc/lustre2/yuyangyang/data/rnaseq_2016/SRR1796465_1.fastq.gz /home/lucas_pkuhpc/lustre2/yuyangyang/data/rnaseq_2016/SRR1796465_2.fastq.gz --outFileNamePrefix rna_seq_SRR1796465 
 pkurun-fat4way 1 16 $(STAR_CMD) --readFilesIn /home/lucas_pkuhpc/lustre2/yuyangyang/data/rnaseq_2016/SRR1796466_1.fastq.gz /home/lucas_pkuhpc/lustre2/yuyangyang/data/rnaseq_2016/SRR1796466_2.fastq.gz --outFileNamePrefix rna_seq_SRR1796466
 pkurun-fat4way 1 16 $(STAR_CMD) --readFilesIn /home/lucas_pkuhpc/lustre2/yuyangyang/data/rnaseq_2016/SRR1796467_1.fastq.gz /home/lucas_pkuhpc/lustre2/yuyangyang/data/rnaseq_2016/SRR1796467_2.fastq.gz --outFileNamePrefix rna_seq_SRR1796467
 pkurun-fat4way 1 16 $(STAR_CMD) --readFilesIn /home/lucas_pkuhpc/lustre2/yuyangyang/data/rnaseq_2016/SRR1796468_1.fastq.gz /home/lucas_pkuhpc/lustre2/yuyangyang/data/rnaseq_2016/SRR1796468_2.fastq.gz --outFileNamePrefix rna_seq_SRR1796468
 pkurun-fat4way 1 16 $(STAR_CMD) --readFilesIn /home/lucas_pkuhpc/lustre2/yuyangyang/data/rnaseq_2016/SRR1796469_1.fastq.gz /home/lucas_pkuhpc/lustre2/yuyangyang/data/rnaseq_2016/SRR1796469_2.fastq.gz --outFileNamePrefix rna_seq_SRR1796469
 pkurun-fat4way 1 16 $(STAR_CMD) --readFilesIn /home/lucas_pkuhpc/lustre2/yuyangyang/data/rnaseq_2016/SRR1796470_1.fastq.gz /home/lucas_pkuhpc/lustre2/yuyangyang/data/rnaseq_2016/SRR1796470_2.fastq.gz --outFileNamePrefix rna_seq_SRR1796470
 pkurun-fat4way 1 16 $(STAR_CMD) --readFilesIn /home/lucas_pkuhpc/lustre2/yuyangyang/data/rnaseq_2016/SRR1796471_1.fastq.gz /home/lucas_pkuhpc/lustre2/yuyangyang/data/rnaseq_2016/SRR1796471_2.fastq.gz --outFileNamePrefix rna_seq_SRR1796471
 pkurun-fat4way 1 16 $(STAR_CMD) --readFilesIn /home/lucas_pkuhpc/lustre2/yuyangyang/data/rnaseq_2016/SRR1796472_1.fastq.gz /home/lucas_pkuhpc/lustre2/yuyangyang/data/rnaseq_2016/SRR1796472_2.fastq.gz --outFileNamePrefix rna_seq_SRR1796472
 pkurun-fat4way 1 16 $(STAR_CMD) --readFilesIn /home/lucas_pkuhpc/lustre2/yuyangyang/data/rnaseq_2016/SRR1796473_1.fastq.gz /home/lucas_pkuhpc/lustre2/yuyangyang/data/rnaseq_2016/SRR1796473_2.fastq.gz --outFileNamePrefix rna_seq_SRR1796473
 pkurun-fat4way 1 16 $(STAR_CMD) --readFilesIn /home/lucas_pkuhpc/lustre2/yuyangyang/data/rnaseq_2016/SRR1796474_1.fastq.gz /home/lucas_pkuhpc/lustre2/yuyangyang/data/rnaseq_2016/SRR1796474_2.fastq.gz --outFileNamePrefix rna_seq_SRR1796474
 pkurun-fat4way 1 16 $(STAR_CMD) --readFilesIn /home/lucas_pkuhpc/lustre2/yuyangyang/data/rnaseq_2016/SRR1796475_1.fastq.gz /home/lucas_pkuhpc/lustre2/yuyangyang/data/rnaseq_2016/SRR1796475_2.fastq.gz --outFileNamePrefix rna_seq_SRR1796475
 pkurun-fat4way 1 16 $(STAR_CMD) --readFilesIn /home/lucas_pkuhpc/lustre2/yuyangyang/data/rnaseq_2016/SRR1796476_1.fastq.gz /home/lucas_pkuhpc/lustre2/yuyangyang/data/rnaseq_2016/SRR1796476_2.fastq.gz --outFileNamePrefix rna_seq_SRR1796476
 
 
